In [53]:
import numpy as np

## DataTypes & Attributes

In [54]:
# NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [55]:
type(a1)

numpy.ndarray

In [56]:
a2 = np.array([[1,2.0,3.3],[4,5,6.5]])
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [57]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [58]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [59]:
a1.shape

(3,)

In [60]:
a2.shape

(2, 3)

In [61]:
a3.shape

(2, 3, 3)

In [62]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [63]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [64]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [65]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [66]:
# create a DataFrame from Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating numpy arrays

In [67]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [68]:
sample_array.dtype

dtype('int64')

In [69]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [70]:
ones.dtype

dtype('float64')

In [71]:
type(ones)

numpy.ndarray

In [72]:
zeros = np.zeros((2,3))

In [73]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [74]:
zeros.shape

(2, 3)

In [76]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [79]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[8, 2, 1, 9, 5],
       [8, 7, 5, 9, 4],
       [7, 3, 8, 3, 6]])

In [80]:
random_array.size

15

In [81]:
random_array.shape


(3, 5)

In [82]:
random_array_2= np.random.random((5,3))
random_array_2

array([[0.46539967, 0.73063474, 0.89368366],
       [0.11284048, 0.37241494, 0.97227506],
       [0.58027541, 0.94042098, 0.92899546],
       [0.77521932, 0.62055433, 0.11455584],
       [0.60527144, 0.1154103 , 0.54630475]])

In [83]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[5.42641813e-01, 8.27428731e-01, 9.11476573e-01],
       [8.83909383e-01, 6.19470909e-01, 6.20455142e-01],
       [2.26360198e-01, 1.28380438e-04, 4.54026072e-01],
       [1.61807884e-01, 7.47092838e-01, 5.81064458e-01],
       [1.99866589e-01, 4.68168468e-01, 2.49709226e-01]])

In [ ]:
# Pseudo-random numbers
np.random.seed(seed = 0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [93]:
np.random.seed(seed=7)
random_array_5 = np.random.randint(10, size=(5, 3))
random_array_5

array([[4, 9, 6],
       [3, 3, 7],
       [7, 9, 7],
       [8, 9, 8],
       [7, 6, 4]])

## Viewing arrays and matrices

In [94]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
a1, a2, a3

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [96]:
a1[0]

np.int64(1)

In [98]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [99]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [100]:
a4 = np.random.randint(10,size=(2,3,4,5))

In [101]:
a4

array([[[[0, 7, 0, 7, 6],
         [3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7]],

        [[3, 3, 8, 3, 0],
         [1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4]],

        [[3, 1, 3, 1, 3],
         [4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0]]],


       [[[9, 9, 3, 4, 5],
         [3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5]],

        [[7, 1, 5, 4, 4],
         [9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6]],

        [[9, 8, 6, 5, 9],
         [7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4]]]])

In [102]:
a4.shape, a4.ndim, a4.size

((2, 3, 4, 5), 4, 120)

In [107]:
# Get the first 4 numbers of the inner most array
a4[:,:,:2,:2]

array([[[[0, 7],
         [3, 5]],

        [[3, 3],
         [1, 0]],

        [[3, 1],
         [4, 3]]],


       [[[9, 9],
         [3, 0]],

        [[7, 1],
         [9, 9]],

        [[9, 8],
         [7, 5]]]])