In [3]:
import numpy as np

## DataTypes & Attributes

In [4]:
# NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1,2.0,3.3],[4,5,6.5]])
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [7]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [14]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [16]:
# create a DataFrame from Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating numpy arrays

In [17]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [18]:
sample_array.dtype

dtype('int64')

In [19]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [21]:
type(ones)

numpy.ndarray

In [22]:
zeros = np.zeros((2,3))

In [23]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
zeros.shape

(2, 3)

In [25]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [26]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[2, 8, 7, 5, 2],
       [6, 4, 9, 8, 2],
       [8, 6, 0, 6, 6]])

In [27]:
random_array.size

15

In [28]:
random_array.shape


(3, 5)

In [29]:
random_array_2= np.random.random((5,3))
random_array_2

array([[0.78707969, 0.15425081, 0.84513809],
       [0.50264242, 0.81554471, 0.40315216],
       [0.22528888, 0.09140293, 0.71684687],
       [0.84752736, 0.50438903, 0.73322339],
       [0.63268043, 0.38028422, 0.77314789]])

In [30]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.57324086, 0.7596926 , 0.20823529],
       [0.63098768, 0.49564685, 0.91493391],
       [0.35254039, 0.07181873, 0.33698354],
       [0.28219055, 0.68336815, 0.8922843 ],
       [0.17629082, 0.55410379, 0.76071728]])

In [31]:
# Pseudo-random numbers
np.random.seed(seed = 0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [32]:
np.random.seed(seed=7)
random_array_5 = np.random.randint(10, size=(5, 3))
random_array_5

array([[4, 9, 6],
       [3, 3, 7],
       [7, 9, 7],
       [8, 9, 8],
       [7, 6, 4]])

## Viewing arrays and matrices

In [33]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a1, a2, a3

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [35]:
a1[0]

np.int64(1)

In [36]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [37]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [38]:
a4 = np.random.randint(10,size=(2,3,4,5))

In [39]:
a4

array([[[[0, 7, 0, 7, 6],
         [3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7]],

        [[3, 3, 8, 3, 0],
         [1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4]],

        [[3, 1, 3, 1, 3],
         [4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0]]],


       [[[9, 9, 3, 4, 5],
         [3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5]],

        [[7, 1, 5, 4, 4],
         [9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6]],

        [[9, 8, 6, 5, 9],
         [7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4]]]])

In [40]:
a4.shape, a4.ndim, a4.size

((2, 3, 4, 5), 4, 120)

In [41]:
# Get the first 4 numbers of the inner most array
a4[:,:,:2,:2]

array([[[[0, 7],
         [3, 5]],

        [[3, 3],
         [1, 0]],

        [[3, 1],
         [4, 3]]],


       [[[9, 9],
         [3, 0]],

        [[7, 1],
         [9, 9]],

        [[9, 8],
         [7, 5]]]])

## Manipulating and Comparing arays

### Arithmetic

In [42]:
a1

array([1, 2, 3])

In [43]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [44]:
a1+ones

array([2., 3., 4.])

In [45]:
a1 - ones

array([0., 1., 2.])

In [46]:
a1+ones

array([2., 3., 4.])

In [47]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [48]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [49]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [51]:
a1 / ones

array([1., 2., 3.])

In [52]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [53]:
a2//a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [54]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [55]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [56]:
a1 % 2

array([1, 0, 1])

In [57]:
a2%2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

### Aggregation
performing the same operation on a number of things

In [59]:
listy_list = [1,2,3]
type(listy_list)

list

In [60]:
sum(listy_list)

6

In [61]:
a1

array([1, 2, 3])

In [62]:
type(a1)

numpy.ndarray

In [63]:
sum(a1)

np.int64(6)

In [64]:
np.sum(a1)

np.int64(6)

Use Python's methods (`sum()`) on Python datatypes and use NumPy's methods on NumPy arrats (`np.summ`)

In [65]:
# Create a massive Numpy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [66]:
massive_array[:10]

array([0.39200156, 0.93959276, 0.21291858, 0.81329627, 0.40364858,
       0.58672092, 0.18599889, 0.81232251, 0.58084741, 0.44693254])

In [68]:
%timeit sum(massive_array) #python's sum
%timeit np.sum(massive_array) #numpy's np.sum

8.16 ms ± 145 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
31.5 μs ± 42.9 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [69]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [70]:
np.mean(a2)

np.float64(3.6333333333333333)

In [ ]:
np.max(a2)

np.float64(6.5)

In [72]:
np.std(a2)

np.float64(1.8226964152656422)

In [73]:
np.var(a2)

np.float64(3.3222222222222224)