In [49]:
import numpy as np

## DataTypes & Attributes

In [50]:
# NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [51]:
type(a1)

numpy.ndarray

In [52]:
a2 = np.array([[1,2.0,3.3],[4,5,6.5]])
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [53]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [54]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [55]:
a1.shape

(3,)

In [56]:
a2.shape

(2, 3)

In [57]:
a3.shape

(2, 3, 3)

In [58]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [59]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [60]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [61]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [62]:
# create a DataFrame from Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating numpy arrays

In [63]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [64]:
sample_array.dtype

dtype('int64')

In [65]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [66]:
ones.dtype

dtype('float64')

In [67]:
type(ones)

numpy.ndarray

In [68]:
zeros = np.zeros((2,3))

In [69]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [70]:
zeros.shape

(2, 3)

In [71]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [72]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[7, 5, 9, 6, 2],
       [0, 5, 3, 0, 5],
       [7, 1, 8, 4, 9]])

In [73]:
random_array.size

15

In [74]:
random_array.shape


(3, 5)

In [75]:
random_array_2= np.random.random((5,3))
random_array_2

array([[0.78223015, 0.85697563, 0.0336742 ],
       [0.5326448 , 0.79695136, 0.97513968],
       [0.27425859, 0.16910106, 0.87670093],
       [0.90918246, 0.19753289, 0.44152974],
       [0.71923214, 0.84534516, 0.16827531]])

In [76]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.66496896, 0.80783546, 0.54971412],
       [0.16471666, 0.0355288 , 0.28153382],
       [0.80787085, 0.04476626, 0.00821651],
       [0.36161665, 0.06362229, 0.1494863 ],
       [0.02319037, 0.52471984, 0.6966959 ]])

In [77]:
# Pseudo-random numbers
np.random.seed(seed = 0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [78]:
np.random.seed(seed=7)
random_array_5 = np.random.randint(10, size=(5, 3))
random_array_5

array([[4, 9, 6],
       [3, 3, 7],
       [7, 9, 7],
       [8, 9, 8],
       [7, 6, 4]])

## Viewing arrays and matrices

In [79]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
a1, a2, a3

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [81]:
a1[0]

np.int64(1)

In [82]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [83]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [84]:
a4 = np.random.randint(10,size=(2,3,4,5))

In [85]:
a4

array([[[[0, 7, 0, 7, 6],
         [3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7]],

        [[3, 3, 8, 3, 0],
         [1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4]],

        [[3, 1, 3, 1, 3],
         [4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0]]],


       [[[9, 9, 3, 4, 5],
         [3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5]],

        [[7, 1, 5, 4, 4],
         [9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6]],

        [[9, 8, 6, 5, 9],
         [7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4]]]])

In [86]:
a4.shape, a4.ndim, a4.size

((2, 3, 4, 5), 4, 120)

In [87]:
# Get the first 4 numbers of the inner most array
a4[:,:,:2,:2]

array([[[[0, 7],
         [3, 5]],

        [[3, 3],
         [1, 0]],

        [[3, 1],
         [4, 3]]],


       [[[9, 9],
         [3, 0]],

        [[7, 1],
         [9, 9]],

        [[9, 8],
         [7, 5]]]])

## Manipulating and Comparing arays

### Arithmetic

In [88]:
a1

array([1, 2, 3])

In [89]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [90]:
a1+ones

array([2., 3., 4.])

In [91]:
a1 - ones

array([0., 1., 2.])

In [92]:
a1+ones

array([2., 3., 4.])

In [93]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [94]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [95]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [96]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
a1 / ones

In [ ]:
a2 / a1

In [ ]:
a2//a1

In [ ]:
a2 ** 2

In [ ]:
np.square(a2)

In [ ]:
a1 % 2

In [ ]:
a2%2

### Aggregation
performing the same operation on a number of things

In [ ]:
listy_list = [1,2,3]
type(listy_list)

In [ ]:
sum(listy_list)

In [ ]:
a1

In [ ]:
type(a1)

In [ ]:
sum(a1)

In [ ]:
np.sum(a1)

Use Python's methods (`sum()`) on Python datatypes and use NumPy's methods on NumPy arrats (`np.summ`)

In [ ]:
# Create a massive Numpy array
massive_array = np.random.random(100000)
massive_array.size

In [ ]:
massive_array[:10]

In [ ]:
%timeit sum(massive_array) #python's sum
%timeit np.sum(massive_array) #numpy's np.sum

In [ ]:
a2

In [ ]:
np.mean(a2)

In [ ]:
np.max(a2)

In [ ]:
np.std(a2)

In [ ]:
np.var(a2)

In [ ]:
# Demo of std and var
high_var_array = np.array([1,100,200,300,4000, 5000])
low_var_array = np.array([2,4,6,8,10])

In [ ]:
np.var(high_var_array), np.var(low_var_array)

In [ ]:
np.std(high_var_array), np.std(low_var_array)

In [ ]:
np.mean(high_var_array), np.mean(low_var_array)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.hist(high_var_array)
plt.show()

In [ ]:
plt.hist(low_var_array)
plt.show()

### Reshaping and Transposing 

In [ ]:
a2

In [ ]:
a2.shape

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a2*a3

In [ ]:
a2

In [ ]:
a2_reshaped = a2.reshape(2,3,1)
a2_reshaped

In [ ]:
a2_reshaped * a3

In [ ]:
# Transpose
a2.T

In [ ]:
a2.T.shape

In [ ]:
a3

In [ ]:
a3.T

## Dot Product

In [ ]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

mat1

In [ ]:
mat2

In [ ]:
# Element wise multiplication (Hadamard product)
mat1*mat2

In [ ]:
# Dot product
np.dot(mat1, mat2.T)

## Dot product example (nut butter sales)

In [ ]:
np.random.seed(0)
# Number of jars sold
sales_amounts = np.random.randint(20,size=(5,3))
sales_amounts

In [ ]:
# Create a weekly sales DataFrame
weekly_sales = pd.DataFrame(
    sales_amounts,
    index=["Mon", "tues", "Wed", "Thurs", "Fri"],
    columns=["Almond butter", "Peanut butter", "Cashew butter"],
)
weekly_sales

In [ ]:
# Create prices array
prices = np.array([10,8,12])
prices

In [ ]:
# Create butter_prices DataFrame
butter_prices = pd.DataFrame(
    prices.reshape(1,3), index=["Price"], columns=["Almond butter", "Peanut butter", "Cashew butter"]
)
butter_prices

In [ ]:
total_sales= prices.dot(sales_amounts.T)
total_sales

In [ ]:
# Create daily_sales
butter_prices.shape, weekly_sales.shape

In [ ]:
weekly_sales

In [ ]:
daily_sales= butter_prices.dot(weekly_sales.T)
daily_sales

In [ ]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

### Comparison Operators

In [ ]:
a1

In [ ]:
a2

In [ ]:
a2 > a2

In [ ]:
bool_array = a1 >= a2
bool_array

In [ ]:
a1 > 5

In [ ]:
a1 < 5

In [ ]:
a1 == a1

In [ ]:
a1 == a2

## Sorting arrays

In [ ]:
random_array = np.random.randint(10,size=(3,5))
random_array

In [ ]:
np.sort(random_array)

In [ ]:
np.argsort(random_array)

In [ ]:
a1

In [ ]:
np.argsort(a1)

In [ ]:
np.argmin(a1)

In [ ]:
random_array

In [ ]:
np.argmax(random_array, axis=0)

In [97]:
np.argmax(random_array, axis=1)

array([2, 1, 4])

## Practical example numpy in action

<img src="./data/numpy-images/panda.png" />

In [98]:
# Turn image into numpy array
from matplotlib.image import imread

panda = imread("./data/numpy-images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [99]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [100]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [101]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

<img src="./data/numpy-images/car-photo.png" />

In [103]:
car = imread("./data/numpy-images/car-photo.png")
car[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]],
      shape=(1, 575, 4), dtype=float32)

<img src="./data/numpy-images/dog-photo.png" />

In [104]:
dog = imread("./data/numpy-images/dog-photo.png")
dog[:1]

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]]],
      shape=(1, 575, 4), dtype=float32)